CREATE PROC DATAINSERT (
		@STUDENTNO VARCHAR(50),
		@STUDENTNAME VARCHAR(50),
		@STUDENTLASNAME VARCHAR(50)
)
AS
BEGIN
			IF NOT EXISTS (SELECT * FROM STUDENT WHERE @STUDENTNO = NO)
			BEGIN
					INSERT INTO STUDENT (NO,NAME,LASTNAME)
					SELECT 
							@STUDENTNO,
							@STUDENTNAME,
							@STUDENTLASNAME
					SELECT 'THE REGISTRATION WAS SUCCESSFULLY COMPLETED'

			END
			ELSE
			BEGIN
					UPDATE STUDENT SET
					NAME=@STUDENTNAME,
					LASTNAME = @STUDENTLASNAME

			WHERE STUDENTNO = @STUDENTNO
			SELECT 'REGISTRATION HAS BEEN COMPLETED'

		END
END