CREATE PROC DeleteRecord(
		@ID INT
)
AS
BEGIN

			IF  EXISTS (SELECT * FROM STUDENT WHERE @ID = ID AND STATU =1)
			BEGIN
					DELETE FROM  STUDENT  WHERE ID =@ID
					UPDATE STUDENT SET STATU =0 WHERE ID = @ID
					SELECT 'THE REGISTRATION HAS BEEN DELETED'
				
			END
			ELSE
					SELECT 'THERE IS NO SUCH RECORD'
		END
				
END